---
networks:
  frontend:
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_api_password: ${API_PASSWORD}
    volumes:
      - './etc-pihole:/etc/pihole'
      - './dnsmasq:/etc/dnsmasq.d'
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      # - NET_ADMIN
    restart: unless-stopped
    networks:
      - frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.pihole-http.rule=Host(`pihole.home.sebastian-ratajczak.de`)
      - traefik.http.routers.pihole-http.entrypoints=websecure
      - traefik.http.routers.pihole-http.tls=true
      - traefik.http.routers.pihole-http.tls.certresolver=ovh
      - traefik.http.services.pihole-service.loadBalancer.server.port=80
