global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
certificatesResolvers:
  ovh:
    acme:
      email: "sebastian@sebastian-ratajczak.de"
      storage: "/var/letsencrypt/acme.json"
      dnsChallenge:
        provider: "ovh"
        delayBeforeCheck: 10
        resolvers:
          - 1.1.1.1
          - 1.0.0.1
          - 9.9.9.9