global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
certificatesResolvers:
  myresolver:
    acme:
      email: "sebastian@sebastian-ratajczak.de"
      storage: "acme.json"
      dnsChallenge:
        provider: "ovh"
        delayBeforeCheck: 10